stages:
    - test
    - deploy
    
test job:
   tags: 
     - integration
   stage: test
   only:
     - integration
   script:
     - cd /web/www && sudo git checkout integration
     - sudo git pull origin integration
     - sudo docker stop cs1_instance || true && sudo docker rm cs1_instance || true
     - cd /web && sudo docker build -t chatscrum .
     - sudo docker start jovial_jang && sudo docker start lj_db
     - sudo docker run -d -p 5000:5000 -p 5100:5100 -e "DATABASE_URL=mysql://linuxjobber:8iu7*IU&@lj_db" -e "SESSION_DEFAULTS=database" --link lj_db --link jovial_jang --name cs1_instance chatscrum

deploy:
   stage: deploy
   only:
     - master
   script:
     - cd /web/www && sudo git checkout master
     - sudo git pull origin master
     - sudo docker stop cs1_instance || true && sudo docker rm cs1_instance || true
     - cd /web && sudo docker build -t chatscrum .
     - sudo docker start tender_sinoussi && sudo docker start lj_db
     - sudo docker run -d -p 5000:5000 -p 5100:5100 -e "DATABASE_URL=mysql://linuxjobber:8iu7*IU&@lj_db" -e "SESSION_DEFAULTS=database" --link lj_db --link tender_sinoussi --name cs1_instance chatscrum

